def replace_identity(sql_file, output_file):
    try:
        # Read the SQL file
        with open(sql_file, 'r') as file:
            sql_content = file.read()

        # Replace 'GENERATED AS IDENTITY' with 'GENERATED BY DEFAULT AS IDENTITY'
        updated_content = sql_content.replace('GENERATED AS IDENTITY', 'GENERATED BY DEFAULT AS IDENTITY')

        # Write the updated content to a new SQL file
        with open(output_file, 'w') as file:
            file.write(updated_content)

        print(f"Updated SQL has been written to {output_file}")

    except Exception as e:
        print(f"An error occurred: {e}")

# Usage
replace_identity('CreateTable.sql', 'UpdatedCreateTable.sql')
